[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "1.4.0"
update_changelog_on_bump = true

version_files = [
    ".cz.toml",
    "prerequisites.py:__version__"
]
